// packages/vant-cli/site/mobile/components/DemoHomeNav.vue
<template>
  <div class="demo-home-nav">
    <div class="demo-home-nav__title">{{ group.title }}</div>
    <div class="demo-home-nav__group">
      <router-link
        class="demo-home-nav__block"
        v-for="navItem in group.items"
        :key="navItem.path"
        :to="`${base}/${navItem.path}`"
      >
        {{ navItem.title }}
        <arrow-right class="demo-home-nav__icon" />
      </router-link>
    </div>
  </div>
</template>

<script>
import ArrowRight from './ArrowRight.vue';

export default {
  components: {
    ArrowRight,
  },

  props: {
    lang: String,
    group: Object,
  },

  data() {
    return {
      active: [],
    };
  },

  computed: {
    base() {
      return this.lang ? `/${this.lang}` : '';
    },
  },
};
</script>

<style lang="less">
.demo-home-nav {
  &__title {
    margin: 24px 0 8px 16px;
    color: rgba(69, 90, 100, 0.6);
    font-size: 14px;
  }

  &__block {
    position: relative;
    display: flex;
    margin: 0 0 12px;
    padding-left: 20px;
    color: #323233;
    font-weight: 600;
    font-size: 14px;
    line-height: 40px;
    background: #f7f8fa;
    border-radius: 99px;
    transition: background 0.3s;

    &:hover {
      background: darken(#f7f8fa, 3%);
    }

    &:active {
      background: darken(#f7f8fa, 6%);
    }
  }

  &__icon {
    position: absolute;
    top: 50%;
    right: 16px;
    width: 16px;
    height: 16px;
    margin-top: -8px;
  }
}
</style>

// packages/vant-cli/site/mobile-react/components/home/DemoHomeNav.tsx
import { Link } from 'react-router-dom';

function ArrowRight() {
  return (
    <svg className="demo-home-nav__icon" viewBox="0 0 1024 1024">
      <path
        fill="#B6C3D2"
        d="M601.1 556.5L333.8 289.3c-24.5-24.5-24.5-64.6 0-89.1s64.6-24.5 89.1 0l267.3 267.3c24.5 24.5 24.5 64.6 0 89.1-24.5 24.4-64.6 24.4-89.1-.1z"
      />
      <path
        fill="#B6C3D2"
        d="M690.2 556.5L422.9 823.8c-24.5 24.5-64.6 24.5-89.1 0s-24.5-64.6 0-89.1l267.3-267.3c24.5-24.5 64.6-24.5 89.1 0 24.5 24.6 24.5 64.6 0 89.1z"
      />
    </svg>
  );
}

export function DemoHomeNav(props: { group: any; lang: string }) {
  const base = props.lang ? `/${props.lang}` : '';
  return (
    <div className="demo-home-nav">
      <div className="demo-home-nav__title">{props.group.title}</div>
      <div className="demo-home-nav__group">
        {props.group.items.map((navItem: any) => (
          <Link
            to={`${base}/${navItem.path}`}
            className="demo-home-nav__block"
            key={navItem.title}
          >
            {navItem.title}
            <ArrowRight />
          </Link>
        ))}
      </div>
    </div>
  );
}
