// packages/vant-cli/site/mobile-react/App.tsx
import { useNavigate, useRoutes, useLocation } from 'react-router-dom';
import { routesConfig } from './router';

import { getDefaultTheme } from '../common/iframe-sync';
import { config } from 'site-mobile-shared';

import './index.less';
import { Suspense, useEffect, useState } from 'react';
import { DemoSection } from './components/DemoSection';

function App() {
  const navigate = useNavigate();
  const location = useLocation();
  useEffect(() => {
    window.top &&
      window.top.postMessage(
        {
          type: 'replacePath',
          value: location.pathname,
        },
        '*'
      );
  }, [location]);
  window.addEventListener('message', (event) => {
    if (event.data?.type !== 'replacePath') {
      return;
    }

    const path = event.data?.value || '';
    // should preserve hash for anchor
    if (path !== location.pathname) {
      navigate(path);
    }
  });
  const [theme, setTheme] = useState(getDefaultTheme());
  window.addEventListener('message', (event) => {
    if (event.data?.type !== 'updateTheme') {
      return;
    }

    const newTheme = event.data?.value || '';
    setTheme(newTheme);
  });
  useEffect(() => {
    document.documentElement.classList.remove(
      `van-doc-theme-${theme === 'dark' ? 'light' : 'dark'}`
    );
    document.documentElement.classList.add(`van-doc-theme-${theme}`);

    const { darkModeClass, lightModeClass } = config.site;
    if (darkModeClass) {
      document.documentElement.classList.toggle(
        darkModeClass,
        theme === 'dark'
      );
    }
    if (lightModeClass) {
      document.documentElement.classList.toggle(
        lightModeClass,
        theme === 'light'
      );
    }
  }, [theme]);

  const RouterEl = useRoutes(routesConfig);
  return (
    <>
      <DemoSection>
        <Suspense fallback={<h2>Loading</h2>}>{RouterEl}</Suspense>
      </DemoSection>
    </>
  );
}

export default App;

// packages/vant-cli/site/mobile/App.vue
<template>
  <demo-nav />
  <router-view v-slot="{ Component }">
    <demo-section>
      <keep-alive v-if="shouldKeep">
        <component :is="Component" />
      </keep-alive>
      <component v-else :is="Component" />
    </demo-section>
  </router-view>
</template>

<script>
import { watch, computed } from 'vue';
import DemoNav from './components/DemoNav.vue';
import { useCurrentTheme } from '../common/iframe-sync';
import { config } from 'site-mobile-shared';
import { router } from './router';

const excludePath = ['floating-bubble', 'back-top'];

export default {
  components: { DemoNav },

  setup() {
    const shouldKeep = computed(
      () =>
        !excludePath.some((path) =>
          router.currentRoute.value.path.includes(path)
        )
    );

    const theme = useCurrentTheme();

    watch(
      theme,
      (newVal, oldVal) => {
        document.documentElement.classList.remove(`van-doc-theme-${oldVal}`);
        document.documentElement.classList.add(`van-doc-theme-${newVal}`);

        const { darkModeClass, lightModeClass } = config.site;
        if (darkModeClass) {
          document.documentElement.classList.toggle(
            darkModeClass,
            newVal === 'dark'
          );
        }
        if (lightModeClass) {
          document.documentElement.classList.toggle(
            lightModeClass,
            newVal === 'light'
          );
        }
      },
      { immediate: true }
    );

    return {
      shouldKeep,
    };
  },
};
</script>

<style lang="less">
@import '../common/style/base';

body {
  min-width: 100vw;
  background-color: inherit;
}

.van-doc-theme-light {
  background-color: var(--van-doc-gray-1);
}

.van-doc-theme-dark {
  background-color: var(--van-doc-black);
}

::-webkit-scrollbar {
  width: 0;
  background: transparent;
}
</style>
